apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-dev
  namespace: dev
  labels:
    name: rollouts-dev
    type: rollout
spec:
  replicas: 5
  selector:
    matchLabels:
      app: rollouts-dev
  template:
    metadata:
      labels:
        app: rollouts-dev
        type: rollout-app
    spec:
      containers:
        - name: rollouts-dev
          image: argoproj/rollouts-demo:yellow
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: 32Mi
              cpu: 5m
  strategy:
    canary:
      canaryMetadata:
        annotations:
          role: canary
        labels:
          name: canary-rollouts-dev
          type: canary-rollout
      stableMetadata:
        annotations:
          role: stable
        labels:
          name: stable-rollouts-dev
          type: stable-rollout
      steps:
        - setWeight: 20
        - pause: { duration: 10s }
        - setWeight: 40
        - pause: { duration: 10s }
        - setWeight: 60
        - pause: { duration: 10s }
        - setWeight: 80
        - pause: { duration: 10s }
  revisionHistoryLimit: 2
