apiVersion: v1
kind: Service
metadata:
  name: rollouts-dev-svc
  labels:
    name: rollouts-dev-svc
    type: service
spec:
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: rollouts-dev
