apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
  namespace: dev
  labels:
    app: success-rate
    type: analysistemplate
spec:
  metrics:
    - name: webmetric
      successCondition: result != "404 page not found"
      failureLimit: 2
      provider:
        web:
          url: "http://rollouts-svc-canary.dev.svc.cluster.local:8080"
          timeoutSeconds: 10
          headers:
            - key: header-version
              value: v1
