apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-dev
  namespace: dev
  labels:
    name: rollouts-dev
    type: rollout
spec:
  revisionHistoryLimit: 2
  strategy:
    canary:
      # canaryService: svc-rollouts
      # stableService: svc-rollouts
      trafficRouting:
        istio:
          virtualService:
            name: vs-rollouts
            routes:
              - primary
          destinationRule:
            name: dr-rollouts
            canarySubsetName: canary
            stableSubsetName: stable
  replicas: 2
  selector:
    matchLabels:
      app: rollouts-dev
  template:
    metadata:
      labels:
        app: rollouts-dev
        type: rollout-app
    spec:
      containers:
        - name: rollouts-dev
          image: helloworld:0.0.1
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: 32Mi
              cpu: 5m
