apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-dev
  namespace: dev
  labels:
    app: rollouts-dev
    type: rollout
spec:
  rollbackWindow:
    revisions: 2
  revisionHistoryLimit: 2
  replicas: 3
  selector:
    matchLabels:
      app: rollouts-dev
  template:
    metadata:
      labels:
        app: rollouts-dev
        version: stable
    spec:
      containers:
        - name: rollouts-dev
          image: helloworld:0.0.2
          imagePullPolicy: IfNotPresent
          ports:
            - name: rollouts-port
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: 20Mi
              cpu: 5m
          startupProbe:
            httpGet:
              path: /
              port: rollouts-port
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 30
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: rollouts-port
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 30
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: rollouts-port
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 30
            successThreshold: 1
            failureThreshold: 3
  strategy:
    canary:
      canaryMetadata:
        annotations:
          version: canary
        labels:
          app: rollouts-dev
          version: canary
      stableMetadata:
        annotations:
          version: stable
        labels:
          app: rollouts-dev
          version: stable
      canaryService: rollouts-svc-canary
      stableService: rollouts-svc-stable
      analysis:
        templates:
          - templateName: success-rate
        # analysisRunMetadata:
        #   labels:
        #     type: analysisrun
        args:
          - name: canary-service
            value: rollouts-svc-canary
          - name: stable-service
            value: rollouts-svc-stable
      trafficRouting:
        istio:
          virtualServices:
            - name: rollouts-vs
              routes:
                - primary
      steps:
        - setWeight: 20
        - pause: { duration: 10s }
        - setWeight: 40
        - pause: { duration: 10s }
        - setWeight: 50
        # - pause: { duration: 10s }
        - pause: {}
        # - setWeight: 80
        # - pause: { duration: 10s }
        # - pause: {}
