# Stable service
apiVersion: v1
kind: Service
metadata:
  name: rollouts-svc-stable
  namespace: dev
  labels:
    app: rollouts-svc-stable
    type: service
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: tcp
  selector:
    app: rollouts-dev
---
# Canary service
apiVersion: v1
kind: Service
metadata:
  name: rollouts-svc-canary
  namespace: dev
  labels:
    app: rollouts-svc-canary
    type: service
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: tcp
  selector:
    app: rollouts-dev
